spring.application.name=tp5-inventario

# Configuración del servidor 
server.port=8080

# Configuración de Swagger / OpenAPI 
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Habilitar DevTools para reinicio automático
spring.devtools.restart.enabled=true
